### ISSUE TITLE
No GPIO real actions happening

### ISSUE THREAD

**Issue by varna33** [krisbreuker/homebridge-gpio-onoff#2]
Install - all went OK.
Set up json file, Hombridge works, and I can switch from Apply Home App the demo GPIO-7 switch on/off, but there is no any real actions happening on the GPIO exit. Also tested the sample light sensor script. The same, all kind of works, but real 3.3/0V status on the GPIO pin is not read.

Why?

**Comment by varna33** [comment]
See homebridge log file, where GPIO-onoff is writing, but nothing happens on real GPIO pin
[3/17/2017, 3:32:00 PM] Loading 0 platforms...
[3/17/2017, 3:32:00 PM] Loading 1 accessories...
[3/17/2017, 3:32:00 PM] [GPIO-7] Initializing GPIO-OnOff accessory...
[3/17/2017, 3:32:00 PM] [GPIO-7] Initializing 'out' GPIO accessory on pin 7
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-111 │     
    └────────────┘     
                       
[3/17/2017, 3:32:00 PM] Homebridge is running on port 51826.
[3/17/2017, 3:32:06 PM] [GPIO-7] Writing Characteristic value 1 as true
[3/17/2017, 3:32:06 PM] [GPIO-7] Wrote GPIO value
[3/17/2017, 3:32:07 PM] [GPIO-7] Writing Characteristic value 0 as false
[3/17/2017, 3:32:07 PM] [GPIO-7] Wrote GPIO value

The GPIO 7 pin always stay at GND.
What is wrong?

**Comment by krisbreuker** [comment]
Is 7 the correct pin number for the GPIO port? The actual number to use may be different depending on the hardware platform you're using.

If the number is correct, can you see if one of the example of the `onoff` package works for you, for example the blinking LED example at https://github.com/fivdi/onoff/blob/master/examples/blink-led.js (`onoff` is the package used to actually write to the GPIO port).

If that works, then maybe the user the runs Homebridge doesn't have the rights to write to the GPIO file system. Non-root users may not be able to enable and disable GPIO ports.

If you found no problems, but it still isn't working, you can try another Homebridge GPIO package to see if it works, like https://www.npmjs.com/package/homebridge-gpio (the package this package is based on).

**Comment by varna33** [comment]
To start with there is something strange with installation one regular jessie. On dietpi i didn't have this issue.

pi@raspberrypi:/ $ sudo npm install -g homebridge-gpio-onoff
\
> epoll@0.1.21 install /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll/build'
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make: Leaving directory '/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll/build'
homebridge-gpio-onoff@0.1.0 /usr/local/lib/node_modules/homebridge-gpio-onoff
└── onoff@1.1.2 (epoll@0.1.21)

**Comment by varna33** [comment]
Also if I create blink-led.js and try to run it
Get following
pi@raspberrypi:/root $ sudo node blink-led.js
module.js:327
    throw err;
    ^

Error: Cannot find module '../onoff'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/blink-led.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
pi@raspberrypi:/root $

**Comment by varna33** [comment]
Installation of onoff package is smooth though
pi@raspberrypi:/root $ npm install onoff
|
> epoll@0.1.21 install /root/node_modules/onoff/node_modules/epoll
> node-gyp rebuild

make: Entering directory '/root/node_modules/onoff/node_modules/epoll/build'
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make: Leaving directory '/root/node_modules/onoff/node_modules/epoll/build'
onoff@1.1.2 node_modules/onoff
└── epoll@0.1.21 (bindings@1.2.1, nan@2.5.1)

**Comment by varna33** [comment]
At the same time this package that also is using onoff works perfect
https://github.com/kraigm/homebridge-gpio-garagedoor

**Comment by krisbreuker** [comment]
There seems to be a problem using `sudo npm`, which creates a readonly directory that cannot be written (`permission to access`), see for example http://stackoverflow.com/questions/29468404/gyp-warn-eacces-user-root-does-not-have-permission-to-access-the-dev-dir.

As this plugin is basically a personal stab at creating a simple read/write GPIO Homebridge plugin, I don't have it installed globally. Instead, I have it checked out in `~/homebridge-plugins` and have Homebridge look in that directory for plugins. That way, I don't have to `sudo` install the package. That is also the reason `npm install onoff` doesn't give an error; you have left out the `sudo`.

As for the `blink-led.js` problem: the first instruction in that file is
```javascript
var Gpio = require('../onoff').Gpio
```
which loads the library from the parent directory, which makes sense within the `onoff` package directory structure. If you want to run it locally, you can checkout the entire `onoff` repository or change it to something like
```javascript
var Gpio = require('onoff').Gpio
```
to load a locally installed `onoff` package.

**Comment by varna33** [comment]
Thank you, but still I didn't get how to fix it.
This is what I did, but still no reaction.
pi@raspberrypi:~ $ cd /usr/local/lib/node_modules
pi@raspberrypi:/usr/local/lib/node_modules $ sudo npm install onoff
|
> epoll@0.1.21 install /usr/local/lib/node_modules/onoff/node_modules/epoll
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/onoff/node_modules/epoll/build'
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make: Leaving directory '/usr/local/lib/node_modules/onoff/node_modules/epoll/build'
onoff@1.1.2 onoff
└── epoll@0.1.21 (bindings@1.2.1, nan@2.5.1)
pi@raspberrypi:/usr/local/lib/node_modules $ sudo npm install -g homebridge-gpio-onoff --unsafe-perm
\
> epoll@0.1.21 install /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll/build'
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make: Leaving directory '/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll/build'
homebridge-gpio-onoff@0.1.0 /usr/local/lib/node_modules/homebridge-gpio-onoff
└── onoff@1.1.2 (epoll@0.1.21)
pi@raspberrypi:/usr/local/lib/node_modules $ sudo adduser $USER gpio
The user `pi' is already a member of `gpio'.

This is directory where are plugins
pi@raspberrypi:/usr/local/lib/node_modules $ ls -l
total 56
drwxr-sr-x 5 pi     pi    4096 Mar 14 14:07 homebridge
drwxr-sr-x 3 nobody pi    4096 Mar 21 20:43 homebridge-gpio
drwxr-sr-x 4 nobody pi    4096 Mar 21 21:33 homebridge-gpio-garagedoor
drwxr-sr-x 3 pi     pi    4096 Mar 22 09:37 homebridge-gpio-onoff
drwxr-sr-x 3 root   staff 4096 Mar 21 21:12 homebridge-gpio-relay
drwxr-sr-x 3 root   staff 4096 Mar 14 14:12 homebridge-gpio-shutter
drwxr-sr-x 4 nobody pi    4096 Mar 14 14:11 homebridge-harmonyhub
drwxr-sr-x 3 nobody pi    4096 Mar 14 14:32 homebridge-people
drwxr-sr-x 4 nobody pi    4096 Mar 14 14:09 homebridge-rcswitch-gpiomem
drwxr-sr-x 3 nobody pi    4096 Mar 14 14:10 homebridge-suncalc
drwxr-sr-x 3 nobody pi    4096 Mar 14 14:12 homebridge-telldus
drwxr-sr-x 3 nobody pi    4096 Mar 14 14:10 homebridge-wol
drwxr-sr-x 9 root   staff 4096 Mar 14 12:15 npm
drwxr-sr-x 5 pi     pi    4096 Mar 22 09:37 onoff

What do you mean with, I don't have such "I have it checked out in ~/homebridge-plugins"

I'm not too much expert in node.js.
Though I got good work done on garage doors, gates opening, and blocking.
But I can't figure out hot to get onoff working.

**Comment by krisbreuker** [comment]
You can specify a specific directory in which to look for plugins using the `-P` argument when starting Homebridge, for example:
```
./bin/homebridge -P ~/homebridge-plugins/
```
So I have my package installed there:
```
cd ~/homebridge-plugins
git clone https://github.com/krisbreuker/homebridge-gpio-onoff.git
```
This is mainly to ease development (see https://github.com/nfarina/homebridge#plugin-development), but it also circumvents the `sudo npm` problem installing `onoff`.

I'm also by no means an expert in Node or Homebridge (or GPIO for that matter), but this is the setup that works for me. This plugin is also work in development, however I haven't had much time to spend on this project unfortunately...

**Comment by varna33** [comment]
And in which directly you have installed onoff?

**Comment by krisbreuker** [comment]
Ah, I forgot to add after the `clone` command:
```
cd homebridge-gpio-onoff
npm install
```
This will install the `onoff` dependency locally within the `homebridge-gpio-onoff` directory, without the use of `sudo npm`.

**Comment by varna33** [comment]
So, in my set-up homebridge and plugins are here, and are found OK.
onoff I placed also there as you see below.

Shall in install in this directory, as I don't have anything like ~/homebridge-plugins?

cd /usr/local/lib/node_modules
ls -l
total 56
drwxr-sr-x 5 pi     pi    4096 Mar 14 14:07 homebridge
drwxr-sr-x 3 nobody pi    4096 Mar 21 20:43 homebridge-gpio
drwxr-sr-x 4 nobody pi    4096 Mar 21 21:33 homebridge-gpio-garagedoor
drwxr-sr-x 3 root   staff 4096 Mar 21 21:12 homebridge-gpio-relay
drwxr-sr-x 3 root   staff 4096 Mar 14 14:12 homebridge-gpio-shutter
drwxr-sr-x 4 nobody pi    4096 Mar 14 14:11 homebridge-harmonyhub
drwxr-sr-x 3 nobody pi    4096 Mar 14 14:32 homebridge-people
drwxr-sr-x 4 nobody pi    4096 Mar 14 14:09 homebridge-rcswitch-gpiomem
drwxr-sr-x 3 nobody pi    4096 Mar 14 14:10 homebridge-suncalc
drwxr-sr-x 3 nobody pi    4096 Mar 14 14:12 homebridge-telldus
drwxr-sr-x 3 nobody pi    4096 Mar 14 14:10 homebridge-wol
drwxr-sr-x 9 root   staff 4096 Mar 14 12:15 npm
drwxr-sr-x 5 pi     pi    4096 Mar 22 09:37 onoff

I did then your set-up instructions

pi@raspberrypi:/usr/local/lib/node_modules $ sudo git clone https://github.com/krisbreuker/homebridge-gpio-onoff.git
Cloning into 'homebridge-gpio-onoff'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 16 (delta 6), reused 16 (delta 6), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.

pi@raspberrypi:/usr/local/lib/node_modules $ cd homebridge-gpio-onoff

pi@raspberrypi:/usr/local/lib/node_modules/homebridge-gpio-onoff $ sudo npm install
\
> epoll@0.1.21 install /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll/build'
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make: Leaving directory '/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll/build'
onoff@1.1.2 node_modules/onoff
└── epoll@0.1.21 (bindings@1.2.1, nan@2.5.1)

Still no reaction, while on HomeKit App all looks working fine, and logs is OK.

[3/22/2017, 10:07:55 AM] [GPIO-40] Wrote GPIO value [3/22/2017, 10:07:55 AM] [GPIO-40] Writing Characteristic value 0 as false
[3/22/2017, 10:07:55 AM] [GPIO-40] Wrote GPIO value [3/22/2017, 10:07:55 AM] [GPIO-40] Writing Characteristic value 1 as true
[3/22/2017, 10:07:54 AM] [GPIO-40] Wrote GPIO value [3/22/2017, 10:07:54 AM] [GPIO-40] Writing Characteristic value 0 as false
[3/22/2017, 10:07:53 AM] [GPIO-40] Wrote GPIO value [3/22/2017, 10:07:53 AM] [GPIO-40] Writing Characteristic value 1 as true
[3/22/2017, 10:07:38 AM] Homebridge is running on port 51826.

031-45-749 I

Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
Load homebridge-harmonyhub.HarmonyHub [3/22/2017, 10:07:38 AM] [GPIO-40] Initializing 'out' GPIO accessory on pin 40
[3/22/2017, 10:07:38 AM] [GPIO-40] Initializing GPIOOnOff accessory...
[3/22/2017, 10:07:38 AM] Loading 1 accessories...
[3/22/2017, 10:07:38 AM] Loading 0 platforms...
[3/22/2017, 10:07:38 AM] ---
[3/22/2017, 10:07:38 AM] Loaded config.json with 1 accessories and 0 platforms.
[3/22/2017, 10:07:38 AM] ---


The pin number I should use is the physical pin on RPI?

**Comment by krisbreuker** [comment]
I don't think it's a good idea to use `/usr/local/lib/node_modules` as plugins directory. Maybe you can create a directory like `/usr/local/lib/homebridge-plugins`:
```
mkdir /usr/local/lib/homebridge-plugins
cd /usr/local/lib/homebridge-plugins
git clone https://github.com/krisbreuker/homebridge-gpio-onoff.git
cd homebridge-gpio-onoff
npm install
```
Use `npm install` without `sudo` for the last step, that will cause the problems you're describing.

Then you can run Homebridge using
```
./bin/homebridge -P /usr/local/lib/homebridge-plugins/
```

**Comment by varna33** [comment]
without su root rights I can't create anything in /usr/local/lib/
even mkdir /usr/local/lib/homebridge-plugins

therefore sudo or su

**Comment by krisbreuker** [comment]
Ok, but can you do `mkdir ~/homebridge-plugins` instead then? And use that directory for the homebridge-gpio-onoff plugin?

**Comment by varna33** [comment]
Did all that, the same (all loads and logs are OK), BUT no real impact on the GPIO pin

pi@raspberrypi:~ $ mkdir ~/homebridge-plugins

pi@raspberrypi:~ $ cd ~/homebridge-plugins

pi@raspberrypi:~/homebridge-plugins $ git clone https://github.com/krisbreuker/homebridge-gpio-onoff.git
Cloning into 'homebridge-gpio-onoff'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 16 (delta 6), reused 16 (delta 6), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.

pi@raspberrypi:~/homebridge-plugins $ cd homebridge-gpio-onoff

pi@raspberrypi:~/homebridge-plugins/homebridge-gpio-onoff $ npm install
/
> epoll@0.1.21 install /home/pi/homebridge-plugins/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll
> node-gyp rebuild

make: Entering directory '/home/pi/homebridge-plugins/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll/build'
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make: Leaving directory '/home/pi/homebridge-plugins/homebridge-gpio-onoff/node_modules/onoff/node_modules/epoll/build'
onoff@1.1.2 node_modules/onoff
└── epoll@0.1.21 (bindings@1.2.1, nan@2.5.1)

pi@raspberrypi:~ $ homebridge -P ~/homebridge-plugins/
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[3/22/2017, 10:54:05 AM] Loaded plugin: homebridge-gpio-onoff
[3/22/2017, 10:54:05 AM] Registering accessory 'homebridge-gpio-onoff.GPIO-OnOff'
[3/22/2017, 10:54:05 AM] ---
[3/22/2017, 10:54:05 AM] Loaded config.json with 1 accessories and 0 platforms.
[3/22/2017, 10:54:05 AM] ---
[3/22/2017, 10:54:05 AM] Loading 0 platforms...
[3/22/2017, 10:54:05 AM] Loading 1 accessories...
[3/22/2017, 10:54:05 AM] [Switch] Initializing GPIO-OnOff accessory...
[3/22/2017, 10:54:05 AM] [Switch] Initializing 'out' GPIO accessory on pin 40
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-111 │     
    └────────────┘     
                       
[3/22/2017, 10:54:05 AM] Homebridge is running on port 51826.
[3/22/2017, 10:54:57 AM] [Switch] Writing Characteristic value 1 as true
[3/22/2017, 10:54:57 AM] [Switch] Wrote GPIO value
[3/22/2017, 10:54:58 AM] [Switch] Writing Characteristic value 0 as false
[3/22/2017, 10:54:58 AM] [Switch] Wrote GPIO value

this is nano /home/pi/.homebridge/config.json
{
        "accessories": [{
                "accessory": "GPIO-OnOff",
                "name": "Switch",
                "pin": 40,
                "direction": "out"
        }],
        "bridge": {
                "username": "CD:22:3D:E3:CE:81",
                "name": "Sauna",
                "pin": "031-45-111",
                "port": 51826
        },
        "platforms": []
}

**Comment by gcamiro** [comment]
Hello all,
I am having sort of the same issue. I have no errors in my logs. I can toggle the switch from my IOS and I get no errors, but no real change in the pin. I have also installed the garagedoor gpio plugin and works good. If I test the blink.js it works good and toggles the pin.
My homebridge is running as homebridge user, and my modules are nobody:pi. But the garagedoor gpio works perfect. Can anybody guide me in the proper direction? 
One thing I noticed also is that after I try the blink.js code I get a warning from IOS at the switch, and in the logs I notice this:

Before using blink.js
[Facade Lights] Writing Characteristic value 1 as true
[Facade Lights] Wrote GPIO value

After using blink.js
[Facade Lights] Writing Characteristic value 1 as true
{there is no second line}

If I restart homebridge "sudo systemctl restart homebridge" it works again.

Now, the real issue is that npm onoff can write to the pin, gpio-onoff cannot.

Please...
