### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by daniel4099** [krisbreuker/homebridge-gpio-onoff#4]
Hi

Running home bridge, I Get the fallowing issue:

[6/10/2017, 12:39:18 AM] Warning: skipping plugin found at '/node_modules/homebridge-gpio-onoff' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-gpio-onoff'.
[6/10/2017, 12:39:19 AM] ====================
[6/10/2017, 12:39:19 AM] ERROR LOADING PLUGIN homebridge-gpio-onoff:
[6/10/2017, 12:39:19 AM] Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/build/epoll.node
 → /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/build/Debug/epoll.node
 → /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/build/Release/epoll.node
 → /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/out/Debug/epoll.node
 → /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/Debug/epoll.node
 → /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/out/Release/epoll.node
 → /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/Release/epoll.node
 → /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/build/default/epoll.node
 → /usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/compiled/7.10.0/linux/arm/epoll.node
    at bindings (/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/epoll/epoll.js:1:99)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-gpio-onoff/node_modules/onoff/onoff.js:4:11)

**Comment by cequn** [comment]
I got the same error, how to figure this out?
